### ISSUE TITLE
body ID

### ISSUE THREAD

**Issue by evovinetu** [rwebber/kinect2share#1]
Is there a way to see which body ID is assigned in OSC output?
Or assign it manually, e.g. if there is one body, it's ID is always 1.

**Comment by rwebber** [comment]
The Kinect assigns the ID, and not always starting with 1.
 My Current method of determining this is simply to watching which OSC channels are active. If the channel is receiving data then the related body is being tracked.
(note: in JSON mode, OSC is always sent for each body, but additional values only exist if the body is being tracked, so check for the existence of these)
